JJCloud_V1/JJCloud_V1/Controllers/WSHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JJCloud_V1.Controllers
{
    public class WSHomeController : Controller
    {
        // GET: WSHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

JJCloud_V1/JJCloud_V1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/myChanges")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ng-grid")
    @Scripts.Render("~/bundles/d3")
    @RenderSection("scripts", required: false)
</head>
<body ng-app="myApp">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JJ Plataform", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("WS Console", "Index", "WSHome", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <script src="http://172.20.10.10:1463/signalr/hubs"></script>
    <script src="http://localhost:1461/signalr/hubs"></script>
    <div class="container-fluid" id="myBody">
        @RenderBody()
    </div>

    <footer>
        <div class="container-fluid">
            <p class="text-muted">Copyright &copy; @DateTime.Now.Year Joaquim Pereira Nº32295 & João Soares Nº32497. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>